FROM node:10
RUN apt-get update && apt-get install -y phantomjs
WORKDIR /app
COPY package*.json ./
RUN npm config set registry https://registry.npm.taobao.org
ENV QT_QPA_PLATFORM offscreen
RUN npm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}

EXPOSE 3000
CMD npm start -- --hostname 0.0.0.0
